### ISSUE TITLE
[flash-swap] Handle division by zero in "getRepayAmount" function

### ISSUE THREAD

**Issue by paulrberg** [hifi-finance/hifi#68]
While working on #67, I realized that there is an edge case which is currently not handled by the Uniswap v2 flash swap contract:

```text
AssertionError: Expected transaction to be reverted with FlashUniswapV2__TurnoutNotSatisfied, but other exception was thrown: Error: VM Exception while processing transaction: reverted with panic code 0x12 (Division or modulo division by zero)
```

That error originates in the `getRepayAmount` function, when the `underlyingReserves` happens to match `underlyingAmount`. The Uniswap v2 pair contract will check for the latter to not be greater than the former, but it will allow it to pass when they are equal. That is because it is possible to have a big amount of one token and a zero amount of the other token in a Uniswap v2 pool.

I can't think off a solution off the top of my head.

**Comment by scorpion9979** [comment]
> The Uniswap v2 pair contract will check for the latter to not be greater than the former, but it will allow it to pass when they are equal.

I don't think the above premise is valid. I think this edge case is never reachable due to [line 162](https://github.com/Uniswap/v2-core/blob/master/contracts/UniswapV2Pair.sol#L162) in the Uniswap V2 pair contract:
```solidity
require(amount0Out < _reserve0 && amount1Out < _reserve1, 'UniswapV2: INSUFFICIENT_LIQUIDITY');
```
When `underlyingReserves` happens to match `underlyingAmount`, that means either `amount0Out` matches `_reserve0` or `amount1Out` matches `_reserve1`. Which leads to the swap function call being reverted with `UniswapV2: INSUFFICIENT_LIQUIDITY` even before `uniswapV2Call(...)` is entered.

**Comment by scorpion9979** [comment]
Yeah, I think it should be closed.
