### ISSUE TITLE
[protocol] Issue concerning wrong param ordering in emitted `RepayBorrow` event

### ISSUE THREAD

**Issue by scorpion9979** [hifi-finance/hifi#76]
From [IBalanceSheetV1.sol#L51](https://github.com/hifi-finance/hifi/blob/9a0e79d4b61f6bf60e48c9018f23254057e2dd96/packages/protocol/contracts/core/balanceSheet/IBalanceSheetV1.sol#L51), we notice that `RepayBorrow` is defined to have `payer` is the first param of the event and `borrower` as the second. But if we go to [BalanceSheetV1.sol#L628](https://github.com/hifi-finance/hifi/blob/9a0e79d4b61f6bf60e48c9018f23254057e2dd96/packages/protocol/contracts/core/balanceSheet/BalanceSheetV1.sol#L628), we see that the emitted event has the params in the opposite order.
I discovered this while investigating a bug in the subgraph that was causing the event-based debt amount calculation to return negative values.

**Comment by scorpion9979** [comment]
@paulrberg The links are now fixed.

**Comment by paulrberg** [comment]
Fixed in https://github.com/hifi-finance/hifi/commit/aef49d06dbb7d091e9e8008d58c3e6f19f53a903.

**Comment by paulrberg** [comment]
I was wondering why this hasn't been caught by our tests .. and that's because the [repayBorrowBehalf](https://github.com/hifi-finance/hifi/blob/aef49d06dbb7d091e9e8008d58c3e6f19f53a903/packages/protocol/test/unit/balance-sheet/effects/repayBorrowBehalf.ts) tests didn't check the `RepayBorrow` event.

Just added a passing test in https://github.com/hifi-finance/hifi/commit/f3cb5431edd53945d15557d26d3349858515156e.
